import logging
from dataclasses import dataclass
from typing import List, Optional

import httpx

from app.config import settings
from app.restore_codes import restore_codes

logger = logging.getLogger(__name__)

# The entitlement configured in RevenueCat that the add-on grants.
REVENUECAT_ENTITLEMENT = "pro"
_REVENUECAT_URL = "https://api.revenuecat.com/v1/subscribers/{app_user_id}"

# Dev-only token shape, so the locked and unlocked states can be exercised before
# a store product exists. Refused whenever dev subscriptions are turned off.
DEV_PREFIX = "dev:"

# A restore code carried by a person rather than a device. It resolves to the
# customer id the purchase was made under; the store still decides the rest.
CODE_PREFIX = "code:"


class ReceiptInvalid(Exception):
    """The token did not check out. The caller falls back to the free tier."""


@dataclass(frozen=True)
class Purchase:
    """A verified purchase of the add-on.

    Identified by the store's own transaction id rather than by whoever presented
    it. The token a device sends belongs to an install and is regenerated by a
    reinstall; the transaction belongs to the money and never changes. Keying the
    answer pool on the install handed a fresh pool to anyone who reinstalled.
    """

    id: str
    # How many times the add-on was bought. Each purchase buys its own pool, so
    # buying again has to add answers rather than be swallowed by a row that
    # already exists.
    count: int = 1
    # A development grant, which keeps explicit semantics: it is created and
    # revoked by hand, never inferred from a store.
    dev: bool = False


def _records(subscriber: dict, entitlement: dict) -> List[dict]:
    """Every purchase behind an entitlement, oldest first."""
    product = entitlement.get("product_identifier")
    entries = subscriber.get("non_subscriptions", {}).get(product)
    if entries is None:
        # Subscriptions are one object rather than a list. Ferry does not sell
        # one, but an entitlement configured that way should still resolve.
        entries = subscriber.get("subscriptions", {}).get(product)
    if entries is None:
        return []
    if isinstance(entries, dict):
        entries = [entries]
    records = [e for e in entries if isinstance(e, dict)]
    records.sort(key=lambda e: e.get("purchase_date") or "")
    return records


def _is_real(record: dict) -> bool:
    """Whether a purchase was made with real money.

    A sandbox purchase grants the same entitlement, with the same name, bought
    with a test card, so this flag is the only thing telling them apart. Anything
    unrecognised is treated as sandbox: refusing a real purchase is a support
    ticket, honouring a fake one gives away models that cost money.
    """
    return record.get("is_sandbox") is False


def _purchase(subscriber: dict, entitlement: dict) -> Optional[Purchase]:
    """Which purchase this entitlement rests on, and how many there have been."""
    records = [
        r for r in _records(subscriber, entitlement)
        if _is_real(r) or settings.allow_sandbox_purchases
    ]
    if not records:
        logger.warning("no usable purchase behind the entitlement; treating as free tier")
        return None

    # The oldest, so the pool stays in one place as later purchases are added to it.
    oldest = records[0]
    purchase_id = oldest.get("store_transaction_id") or oldest.get("id")
    if not purchase_id:
        logger.warning("a purchase arrived with no transaction id; treating as free tier")
        return None
    return Purchase(id=str(purchase_id), count=len(records))


def customer_for(token: str) -> str:
    """The store's customer behind a receipt, following a restore code.

    A device restoring with a code is a different install from the one that
    bought. Anything recorded against this install rather than that customer —
    a second purchase, most of all — would land in a pool the relay never adds
    to the first.
    """
    if token.startswith(CODE_PREFIX):
        return restore_codes.resolve(token[len(CODE_PREFIX):]) or token
    return token


async def verify_receipt(token: str) -> Optional[Purchase]:
    """Return the purchase behind a verified receipt, or None.

    None means "no paid entitlement", never an error: a caller without a valid
    receipt is simply on the free tier, which needs no purchase at all.
    """
    if not token:
        return None

    if token.startswith(CODE_PREFIX):
        customer_id = restore_codes.resolve(token[len(CODE_PREFIX):])
        if customer_id is None:
            logger.info("a restore code did not match any purchase")
            return None
        token = customer_id

    if token.startswith(DEV_PREFIX):
        if not settings.allow_dev_subscription:
            logger.info("rejected a dev receipt: dev subscriptions are off")
            return None
        return Purchase(id=token, dev=True)

    if not settings.revenuecat_api_key:
        # Refusing is the safe direction: treating an unverifiable token as paid
        # would hand out the paid models to anyone who sent a made-up string.
        logger.warning("a receipt arrived but REVENUECAT_API_KEY is not set; treating as free tier")
        return None

    try:
        async with httpx.AsyncClient(timeout=10) as client:
            response = await client.get(
                _REVENUECAT_URL.format(app_user_id=token),
                headers={"Authorization": f"Bearer {settings.revenuecat_api_key}"},
            )
        if response.status_code != 200:
            logger.info("RevenueCat rejected the receipt: %s", response.status_code)
            return None
        subscriber = response.json().get("subscriber", {})
        entitlement = subscriber.get("entitlements", {}).get(REVENUECAT_ENTITLEMENT)
        if entitlement is None:
            return None
        return _purchase(subscriber, entitlement)
    except httpx.HTTPError:
        # A store we cannot reach must not silently unlock paid models, nor should
        # it break the free tier — so the caller carries on without the add-on.
        logger.exception("could not reach RevenueCat; treating as free tier")
        return None
